apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 1.3.0
  additionalManifests:
    - URL: https://github.com/knative/net-certmanager/releases/download/knative-v1.3.0/release.yaml
  ingress:
    contour:
      enabled: true
  config:
    # TODO(bobymcbobs): fix default tls cert
    # contour:
    #   default-tls-secret: ${SHARINGIO_PAIR_INSTANCE_SETUP_USERLOWERCASE}/letsencrypt-prod-without-selector
    network:
      ingress-class: contour.ingress.networking.knative.dev
      clusteringress.class: contour.ingress.networking.knative.dev
      certificate-provider: cert-manager
      autocreate-cluster-domain-claims: "true"
      auto-tls: Enabled
      default-external-scheme: HTTP
      http-protocol: Enabled
    defaults:
      container-name-template: "{{.Name}}"
    domain:
      ${SHARINGIO_PAIR_BASE_DNS_NAME}: ""
    certmanager:
      issuerRef: |
        kind: ClusterIssuer
        name: letsencrypt-prod-without-selector
