apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $.ResourceName }}
  namespace: {{ $.PodNamespace }}
  annotations:
    kubernetes.io/ingress.class: {{ $.IngressClassName }}
  labels:
    io.sharing.pair/managed: "true"
    io.sharing.pair/port: "{{ $.Port }}"
    io.sharing.pair/pid: "{{ $.Pid }}"
    io.sharing.pair/uid: "{{ $.Uid }}"
spec:
  rules:
    - host: {{ $.IngressHost }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $.ResourceName }}
              servicePort: {{ $.ServicePort }}
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ $.IngressHost }}
      secretName: letsencrypt-prod
