apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.ResourceName }}
  namespace: {{ $.PodNamespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    io.sharing.pair/managed: "true"
    io.sharing.pair/port: "{{ $.Port }}"
    io.sharing.pair/pid: "{{ $.Pid }}"
    io.sharing.pair/uid: "{{ $.Uid }}"
spec:
  rules:
    - host: {{ $.IngressHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.ResourceName }}
                port:
                  number: {{ $.ServicePort }}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ $.IngressHost }}
      secretName: letsencrypt-prod
