apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $SHARINGIO_PAIR_INSTANCE_SETUP_EMAIL
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          rfc2136:
            tsigKeyName: pair
            tsigAlgorithm: HMACMD5
            tsigSecretSecretRef:
              name: tsig-powerdns
              key: powerdns
            nameserver: ${KUBERNETES_CONTROLPLANE_ENDPOINT}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod
  namespace: "${SHARINGIO_PAIR_INSTANCE_SETUP_USERLOWERCASE}"
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.${SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME}"
  dnsNames:
    - "*.${SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME}"
    - "${SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME}"
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: cert-manager-tls
