apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: coredns
  namespace: pair-system
spec:
  chart:
    repository: https://coredns.github.io/helm
    name: coredns
    version: 1.16.3
  releaseName: coredns
  values:
    replicaCount: 2
    image:
      tag: 1.8.6
    rbac:
      create: true
    isClusterService: false
    service:
      externalIPs:
        - ${SHARINGIO_PAIR_LOAD_BALANCER_IP}
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          - name: log
          # Serves a /health endpoint on :8080, required for livenessProbe
          - name: health
            configBlock: |-
              lameduck 5s
          # Serves a /ready endpoint on :8181, required for readinessProbe
          - name: ready
          # Serves a /metrics endpoint on :9153, required for serviceMonitor
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: etcd
            parameters: ${SHARINGIO_PAIR_BASE_DNS_NAME}
            configBlock: |-
              stubzones
              path /skydns
              endpoint http://etcd-client:2379
          # respond to A record ns1.my.pair.sharing.io
          - name: template
            parameters: IN A ${SHARINGIO_PAIR_BASE_DNS_NAME}
            configBlock: |-
              match "ns1.${SHARINGIO_PAIR_BASE_DNS_NAME}"
              answer "{{ .Name }} 60 IN A ${SHARINGIO_PAIR_LOAD_BALANCER_IP}"
              fallthrough
          # response to NS record to point to A IN ns1.my.pair.sharing.io
          - name: template
            parameters: IN NS ${SHARINGIO_PAIR_BASE_DNS_NAME}
            configBlock: |-
              match "${SHARINGIO_PAIR_BASE_DNS_NAME}"
              answer "{{ .Name }} 60 IN NS ns1.${SHARINGIO_PAIR_BASE_DNS_NAME}"
              fallthrough
          # set host authority with NS IN ns1.my.pair.sharing.io as nameserver
          - name: template
            parameters: IN SOA ${SHARINGIO_PAIR_BASE_DNS_NAME}
            configBlock: |-
              answer "ns1.${SHARINGIO_PAIR_BASE_DNS_NAME} 60 IN SOA ns1.${SHARINGIO_PAIR_BASE_DNS_NAME} hostmaster.${SHARINGIO_PAIR_BASE_DNS_NAME}. 11 60 60 60 60"
              fallthrough
