---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  namespace: pair-system
spec:
  type: ClusterIP
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: pair-system
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: pair-system
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.1
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_NAME
              value: "$(HOSTNAME)"
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://$(HOSTNAME).etcd:2379"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://$(HOSTNAME):2380"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: etcd-cluster-1
            - name: ETCD_INITIAL_CLUSTER
              value: etcd-0=http://etcd-0.etcd:2380 #,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: new
            - name: ETCD_DATA_DIR
              value: /var/run/etcd/default.etcd
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - name: data
              mountPath: /var/run/etcd
          command:
            - etcd
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
