apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: coredns
spec:
  chart:
    repository: https://coredns.github.io/helm
    name: coredns
    version: 1.16.3
  releaseName: coredns
  values:
    rbac:
      create: true
    isClusterService: false
    service:
      externalIPs:
        - ${SHARINGIO_PAIR_LOAD_BALANCER_IP}
    zoneFiles:
      - filename: pair-instance.db
        domain: ${SHARINGIO_PAIR_BASE_DNS_NAME}
        contents: |
          ${SHARINGIO_PAIR_BASE_DNS_NAME}.     IN SOA ns1.${SHARINGIO_PAIR_BASE_DNS_NAME}. hostmaster.${SHARINGIO_PAIR_BASE_DNS_NAME}. 11 60 60 60 60
          ${SHARINGIO_PAIR_BASE_DNS_NAME}.     IN NS  ns1.${SHARINGIO_PAIR_BASE_DNS_NAME}.
          ns1.${SHARINGIO_PAIR_BASE_DNS_NAME}. IN A ${KUBERNETES_CONTROLPLANE_ENDPOINT}
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          # Serves a /health endpoint on :8080, required for livenessProbe
          - name: health
            configBlock: |-
              lameduck 5s
          # Serves a /ready endpoint on :8181, required for readinessProbe
          - name: ready
          # Serves a /metrics endpoint on :9153, required for serviceMonitor
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . /etc/resolv.conf
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
          - name: etcd
            parameters: ${SHARINGIO_PAIR_BASE_DNS_NAME}
            configBlock: |-
              stubzones
              path /skydns
              endpoint http://etcd-client:2379
