apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  releaseName: kube-prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 18.0.2
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          emptyDir: {}
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: true
      dashboards:
        default:
          node-exporter:
            gnetId: 1860
            revision: 15
            datasource: Prometheus
          deployments:
            gnetId: 8588
            revision: 1
            datasource: Prometheus
      adminPassword: "admin"
      ingress:
        enabled: true
        hosts:
          - grafana.$SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME
        tls:
          - secretName: letsencrypt-prod
            hosts:
              - grafana.$SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME
