apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: kube-prometheus
spec:
  releaseName: kube-prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    version: 16.1.2
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          emptyDir: {}
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: true
      adminPassword: "admin"
      ingress:
        enabled: true
        hosts:
          - grafana.$SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME
        tls:
          - secretName: letsencrypt-prod
            hosts:
              - grafana.$SHARINGIO_PAIR_INSTANCE_SETUP_BASEDNSNAME
