apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 4.0.1
  values:
    controller:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - ingress-nginx
                topologyKey: kubernetes.io/hostname
              weight: 1
      autoscaling:
        enabled: true
        maxReplicas: ${SHARINGIO_PAIR_INSTANCE_TOTAL_NODES_MAX_REPLICAS}
        minReplicas: ${SHARINGIO_PAIR_INSTANCE_TOTAL_NODES}
        targetCPUUtilizationPercentage: 80
      minAvailable: ${SHARINGIO_PAIR_INSTANCE_TOTAL_NODES}
      ingressClassResource:
        default: true
      service:
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: nginx-ingress
        externalIPs:
          - ${KUBERNETES_CONTROLPLANE_ENDPOINT}
